/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Ads;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-11T11:28:57.691Z")

@Api(value = "listQMAds", description = "the listQMAds API")
public interface ListQMAdsApi {

    @ApiOperation(value = "List quality manager ads", nickname = "listQMAds", notes = "irrelevant ads (under 40 score)", response = List.class, tags={ "Endpoints", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = List.class),
        @ApiResponse(code = 405, message = "Error operation") })
    @RequestMapping(value = "/listQMAds",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Ads>> listQMAds();

}
